<?php
$dbIp = '127.0.0.1';
$dbUser = 'root';//yourid!!
$dbPassword = 'thismeanslove';//yourpassword!!
$dbName = 'babel';
//$dbEncoding = 'latin1';
$dbStart = 600000;//can be randomize
$dbLimit = 100000;
$maxExecutionTime = -1;
$memoryLimit = '128M';

$move_inactive = 1;//1 or 0

//at 2012-11-02, minimum live release is helios
$minimum_project_version = array(
'birt' => '2.6.0',
'datatools' => '1.8',
'dsdp.mtj' => '1.1',
'dsdp.sequoyah' => '1.0',
'dsdp.tm' => '3.2',
'eclipse' => '3.6',
'modeling.emf' => '2.8.0',
'modeling.emf.cdo' => '4.1',
//'modeling.emf.eef' => '999.999.999',//moved all to emft??
'modeling.emf.validation' => '1.4',
'modeling.emft' => '1.0',//leaves only last version
'modeling.emft.eef' => '0.7.1',
'modeling.emft.emf-facet' => '0.1.0',
'modeling.gmf' => '2.1',//leaves only last version
'modeling.gmp.gmf-notation' => '1.4.0',
'modeling.gmp.gmf-runtime' => '1.4.0',
'modeling.gmp.gmf-tooling' => '2.3',
'modeling.gmp.graphiti' => '0.8.0',
//'modeling.gmt.modisco' => '999.999.999',//moved all to mdt??
'modeling.m2m' => '2.0',//leaves only last version
//'modeling.m2t' => '0.0',//I do not know version rule
'modeling.mdt' => '3.0.0',//leaves only last version
'modeling.mdt.modisco' => '0.9.0',
'modeling.mdt.ocl' => '3.0.0',
'modeling.tmf' => '0.7.0',//leaves only last version
'mylyn' => '3.6',
'rt.ecf' => '3.0.0',//leaves only last version
'rt.equinox' => '3.6',
'rt.equinox.p2' => '3.6',
'rt.rap' => '1.3',
//'stp' => '999.999',//to be removed all??
'stp.bpmn' => '1.1',//leaves only last version
'stp.sca' => '2.0',//leaves only last version
'technology.actf' => '0.8.0',
'technology.bpel' => '0.5.0',
'technology.dltk' => '3.0',
'technology.egit' => '0.8.0',
'technology.jgit' => '0.8.1',
'technology.jubula' => '0.9.0',
'technology.jwt' => '0.6.0',//leaves only last version
'technology.koneki' => '0.8',
'technology.linux-distros' => '0.6',
//'technology.mat' => '999.999',//to be removed all?? now may be tools.mat
'technology.packaging' => '1.0.2',//leaves only last version
'technology.packaging.mpc' => '1.0.0',
'technology.stem' => '1.2.1',
'technology.subversive' => '0.8',
'technology.uomo' => '0.6.0',
'tools.atf' => '0.3',
'tools.cdt' => '7.0',
'tools.cdt.tcf' => '1.0',
'tools.gef' => '3.6',
'tools.mat' => '1.0',
'tools.mylyn' => '3.3',
'tools.objectteams' => '2.0',
'tools.orbit' => '999.999.999',//to be removed all
'tools.pdt' => '3.1',
'tools.ptp' => '4.0',
'tools.ptp.photran' => '6.0',
'tools.tm' => '3.2',
'tptp.platform' => '4.6',//leaves only last version
'webtools' => '3.4',
'webtools.common' => '3.2',
'webtools.dali' => '2.3',
'webtools.ejbtools' => '3.2',
'webtools.jeetools' => '3.2',
'webtools.jsdt' => '3.2',
'webtools.jsf' => '3.2',
'webtools.libra' => '0.1',
'webtools.servertools' => '3.2',
'webtools.sourceediting' => '3.2',
'webtools.webservices' => '3.2',
);
