<?php
require 'upd_common.php';

//PDT 2.2 - 3.0 Help
$search = array(
'Viewing JavaScript Elements in the Outline View',
'Setting your Environment to be an Allowed Host',
'Enabling JavaScript Support in PHP Projects',
'Editing PHP Library Components or Folders',
'Removing a PHP Library or Library Folder',
'Creating a  PHP File Outside of a Project',
'Creating a PHP File Outside of a Project',
"Configuring a Project's PHP Include Path",
'Adding External Folders to PHP Libraries',
'Setting your PDT to be an Allowed Host',
'Running and Analyzing Debugger Results',
"Configuring a Project's PHP Build Path",
'Creating a PHP File Within a Project',
'Ensuring the Placement of dummy.php',
'Accessing an Existing CVS Checkout',
'Using JavaScript Mark Occurrences',
'Setting the JavaScript Build Path',
'Adding a Server Location Path Map',
'Using JavaScript Syntax Coloring',
'Debugging Files and Applications',
'Using JavaScript Content Assist',
'Installed Debuggers Preferences',
'Creating and Opening HTML Files',
'Working with Mylyn Integration',
'Running Files and Applications',
'New Project Layout Preferences',
'Locally Debugging a PHP Script',
'Workbench Options Preferences',
'Run/Debug Settings Properties',
'Project References Properties',
'Running PHP Scripts Remotely',
'Mark Occurrences Preferences',
'Importing PHP User Libraries',
'Exporting PHP User Libraries',
'Adding PHP DocBlock Comments',
'Working with Content Assist',
'Tunneling Debug Preferences',
'Syntax Coloring Preferences',
'Setting Up Remote Debugging',
'Running PHP Scripts Locally',
'Mark Occurences Preferences',
'Creating Projects and Files',
'Step Filtering Preferences',
'Searching for PHP Elements',
'Path Variables Preferences',
'Importing from a Phar File',
'Editing PHP User Libraries',
'Developing with JavaScript',
'Content Assist Preferences',
'Code Templates Preferences',
'Working with the Debugger',
'Real Time Error Detection',
'Creating PHP Working Sets',
'Code Templates Properties',
'Working with Code Assist',
'Viewing Type Hierarchies',
//Using the Inspect Action
'Save Actions Preferences',
'Perspective Main Toolbar',
'Opening an External File',
'Debugging a PHP Web Page',
'Creating a new PHAR file',
'Code Folding Preferences',
'Using Smart Goto Source',
'Save Actions Properties',
'Opening Types / Methods',
'Interpreter Preferences',
'Include Path Properties',
'Executables Preferences',
'Configuring Build Paths',
'Code Assist Preferences',
'Using Mark Occurrences',
'Perspectives and Views',
'Managing PHP Libraries',
'Interpreter Properties',
'Code Style Preferences',
'Appearance Preferences',
//What's New in PDT 2.x
"What's New",
'Validation Properties',
'Templates Preferences',
'Task Tags Preferences',
'Running PHP Web Pages',
'phpDoc Block Comments',
'Opening Types/Methods',
'Libraries Preferences',
'Formatter Preferences',
'Creating PHP Projects',
'Code Style Properties',
'Build Path Properties',
'Using Content Assist',
'Task Tags Properties',
'Project Outline View',
'Parameter Stack View',
'Opening PHP Elements',
'Formatter Properties',
'Automatic Completion',
'Adding a PHP Library',
'Using Drag and Drop',
'Type Hierarchy View',
'Setting Breakpoints',
'Servers Preferences',
'Resource Properties',
'Refactoring History',
'Override Indicators',
'Installed Debuggers',
'Folding Preferences',
'Creating PHAR files',
'Builders Properties',
'Browser Output View',
'Using the Debugger',
'Using Code Folding',
'Typing Preferences',
'Project Properties',
'Navigation Submenu',
'Manual Preferences',
'Manual Integration',
'JavaScript Support',
'Hovers Preferences',
'Export PHAR Wizard',
'Editor Preferences',
'Easy File Creation',
'Creating PHP Files',
'Workbench Options',
'Using Code Assist',
'Table of Contents',
'Perspective Menus',
'Mylyn Integration',
'Matching Brackets',
'Debug Preferences',
'Debug Perspective',
'Debug Output View',
'Preferences Page',
'Phar Integration',
'Mark Occurrences',
'Expressions View',
'Debug Properties',
'Breakpoints View',
'Additional Views',
'Video Tutorials',
'Version Support',
'Using Templates',
'Syntax Coloring',
'PHP Preferences',
'PHP Perspective',
'Getting Started',
'Formatting Code',
'Commenting Code',
'Code Commenting',
'Basic Tutorials',
'Adding Comments',
'Variables View',
'Type Hierarchy',
'Functions View',
'Content Assist',
'Refactor Menu',
'Navigate Menu',
'Include Paths',
'Import Wizard',
'Hover Support',
'Explorer View',
'Drag and drop',
'Drag and Drop',
'Working Sets',
'Project Menu',
'Path Mapping',
'Outline View',
'Include Path',
'Code Folding',
'Window Menu',
'Source Menu',
'Search Menu',
'Quick Start',
'PHP Support',
'Code Assist',
'Build Paths',
'User Guide',
'Debug View',
'Build Path',
'Using CVS',
'PHP Icons',
'Help Menu',
'File Menu',
'Edit Menu',
'Run Menu',
'label="Concepts"',
'label="Bookmarks"',
'label="Running"',
'label="Debugging"',
'label="Breakpoints"',
'label="Navigation"',
'label="Reference"',
'label="Refactor"',
'label="Navigate"',
'label="Project"',
'label="Window"',
'label="Source"',
'label="Search"',
'label="Import"',
'label="Export"',
'label="Keymap"',
'label="Tasks"',
'label="Help"',
'label="File"',
'label="Edit"',
'label="Run"',
'label="New"',
' Help</description>',
'    ',
);

$replace = array(
		'アウトライン・ビューで JavaScript 要素を表示',
		'環境を許可されたホストとして設定',
		'PHP プロジェクトで JavaScript サポートを有効にする',
		'PHP ライブラリーコンポーネントまたはフォルダーを編集',
		'PHP ライブラリーまたはライブラリーフォルダーを削除',
		'プロジェクトの外にPHP ファイルを作成',
		'プロジェクトの外にPHP ファイルを作成',
		'プロジェクトの PHP include パスを構成',
		'外部フォルダーを PHP ライブラリーに追加',
		'PDT を許可されたホストとして設定',
		'デバッグの実行および解析',
		'プロジェクトの PHP ビルドパスを構成',
		'プロジェクトの中にPHP ファイルを作成',
		'dummy.php の配置を確認する',
		'既存の CVS チェックアウトにアクセス',
		'JavaScript 出現箇所のマークを使用',
		'JavaScript ビルドパスを設定',
		'サーバーのロケーション・パスマップを追加',
		'JavaScript 構文色分けを使用',
		'ファイルおよびアプリケーションをデバッグ',
		'JavaScript コンテンツ・アシストを使用',
		'インストールされたデバッガー設定',
		'HTML ファイルを作成および開く',
		'Mylyn 統合',
		'ファイルおよびアプリケーションを実行',
		'新規プロジェクトのレイアウト設定',
		'PHP スクリプトをローカル・デバッグ',
		'ワークベンチ・オプション設定',
		'実行・デバッグ設定プロパティー',
		'プロジェクト設定プロパティー',
		'PHP スクリプトをリモート実行',
		'出現箇所のマーク設定',
		'PHP ユーザーライブラリーをインポート',
		'PHP ユーザーライブラリーをエクスポート',
		'PHP DocBlock コメントを追加',
		'コンテンツ・アシスト',
		'トンネリング設定',
		'構文色分け設定',
		'リモート・デバッグを設定',
		'PHP スクリプトをローカル実行',
		'出現箇所のマーク設定',
		'プロジェクトおよびファイルを作成',
		'ステップ・フィルタリング設定',
		'PHP 要素を検索',
		'パス変数設定',
		'Phar ファイルからインポート',
		'PHP ユーザーライブラリーを編集',
		'JavaScript で開発',
		'コンテンツ・アシスト設定',
		'コード・テンプレート設定',
		'デバッガー',
		'リアルタイム・エラー検出',
		'PHP ワーキング・セットを作成',
		'コード・テンプレート・プロパティー',
		'コード・アシスト',
		'型階層を表示',
		//Using the Inspect Action
		'保管設定',
		'パースペクティブ・メイン・ツールバー',
		'外部ファイルを開く',
		'PHP Web 画面をデバッグ',
		'PHAR ファイルを新規作成',
		'コード折りたたみ設定',
		'宣言部を開く',
		'保管プロパティー',
		'型またはメソッドを開く',
		'インタープリター設定',
		'include パス・プロパティー',
		'実行可能ファイル設定',
		'ビルドパスを構成',
		'コード・アシスト設定',
		'出現箇所のマークを使用',
		'パースペクティブとビュー',
		'PHP ライブラリーを管理',
		'インタープリタープロパティー',
		'コード・スタイル設定',
		'外観設定',
		//What's New in PDT 2.x
		'新機能',
		'検証プロパティー',
		'テンプレート設定',
		'タスクタグ設定',
		'PHP Web 画面を実行',
		'phpDoc ブロック・コメント',
		'型またはメソッドを開く',
		'ライブラリー設定',
		'フォーマッター設定',
		'PHP プロジェクトを作成',
		'コード・スタイル・プロパティー',
		'ビルドパス・プロパティー',
		'コンテンツ・アシストを使用',
		'タスク・タグ・プロパティー',
		'プロジェクト・アウトライン・ビュー',
		'パラメータースタック・ビュー',
		'PHP 要素を開く',
		'フォーマッタープロパティー',
		'自動補完',
		'PHP ライブラリーを追加',
		'ドラッグ＆ドロップを使用',
		'型階層ビュー',
		'ブレークポイントを設定',
		'サーバー設定',
		'リソース・プロパティー',
		'リファクタリング履歴',
		'インジケーターを上書き',
		'インストールされたデバッガー',
		'折りたたみ設定',
		'PHAR ファイルを作成',
		'ビルダープロパティー',
		'ブラウザー出力ビュー',
		'デバッガーを使用',
		'コード折りたたみを使用',
		'入力設定',
		'プロジェクト・プロパティー',
		'ナビゲーション・サブメニュー',
		'マニュアル設定',
		'マニュアル統合',
		'JavaScript サポート',
		'ホバー設定',
		'PHAR のエクスポート・ウィザード',
		'エディター設定',
		'簡易ファイル作成',
		'PHP ファイルを作成',
		'ワークベンチ・オプション',
		'コード・アシストを使用',
		'目次',
		'パースペクティブ・メニュー',
		'Mylyn 統合',
		'対応する括弧',
		'デバッグ設定',
		'デバッグ・パースペクティブ',
		'デバッグ出力ビュー',
		'設定画面',
		'Phar 統合',
		'出現箇所のマーク',
		'式ビュー',
		'デバッグ・プロパティー',
		'ブレークポイント・ビュー',
		'追加のビュー',
		'ビデオ・チュートリアル',
		'バージョン・サポート',
		'テンプレートを使用',
		'構文色分け',
		'PHP 設定',
		'PHP パースペクティブ',
		'はじめに',
		'コードを整形',
		'コードをコメント',
		'コードのコメント',
		'基本チュートリアル',
		'コメントを追加',
		'変数ビュー',
		'型階層',
		'関数ビュー',
		'コンテンツ・アシスト',
		'リファクタリング・メニュー',
		'ナビゲート・メニュー',
		'include パス',
		'インポート・ウィザード',
		'ホバーサポート',
		'エクスプローラービュー',
		'ドラッグ＆ドロップ',
		'ドラッグ＆ドロップ',
		'ワーキング・セット',
		'プロジェクト・メニュー',
		'パス・マッピング',
		'アウトライン・ビュー',
		'include パス',
		'コード折りたたみ',
		'ウィンドウ・メニュー',
		'ソース・メニュー',
		'検索メニュー',
		'クイック・スタート',
		'PHP サポート',
		'コード・アシスト',
		'ビルド・パス',
		'ユーザーガイド',
		'デバッグ・ビュー',
		'ビルド・パス',
		'CVS を使用',
		'PHP アイコン',
		'ヘルプ・メニュー',
		'ファイル・メニュー',
		'編集メニュー',
		'実行メニュー',
'label="コンセプト"',
'label="ブックマーク"',
'label="実行"',
'label="デバッグ"',
'label="ブレークポイント"',
'label="ナビゲーション"',
'label="リファレンス"',
'label="リファクタリング"',
'label="ナビゲート"',
'label="プロジェクト"',
'label="ウィンドウ"',
'label="ソース"',
'label="検索"',
'label="インポート"',
'label="エクスポート"',
'label="キーマップ"',
'label="タスク"',
'label="ヘルプ"',
'label="ファイル"',
'label="編集"',
'label="実行"',
'label="新規"',
'</description>',
"\t",
);

/* for org.eclipse.php.help */
$ret = replaceTexts('helpContexts', $search, $replace, 399);
$ret = replaceTexts('maintoc', $search, $replace, 12);
$ret = replaceTexts('toc', $search, $replace, 408);
/* */

echo '<BR>end';